gcp_project_id = ""

[terra]
workspace_namespace = ""
workspace_name = ""
other_workspaces = [
    { "workspace_namespace" = "",  "workspace_name" = "" }
] # optional

[plan]
inventory_path = "./data/inventories/inventory.ndjson"
plan_path = "./data/plans/plan.parquet"
days_considered_old = 30
size_considered_large = 1e6
